substitutions:
  name: atomecho01
  friendly_name: Atom Echo
  static_ip: 192.168.2.186
  micro_wake_word_model: okay_nabu  # alexa, hey_jarvis, hey_mycroft are also supported



esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: false
  project:
    name: m5stack.atom-echo-dev
    version: "1.0"


esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

logger:
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_pwd_sec
#  - platform: http_request
#    id: ota_http_request
#
#update:
#  - platform: http_request
#    id: update_http_request
#    name: Firmware
#    source: https://firmware.esphome.io/wake-word-voice-assistant/m5stack-atom-echo/manifest.json

# dashboard_import:
#   package_import_url: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main

wifi:
  networks:
  - ssid: !secret wifi_dmz_ssid
    password: !secret wifi_dmz_password
  use_address: 192.168.2.186

  #manual_ip:
  #  static_ip: ${static_ip}
  #  gateway: 192.xxxxxxxxx
  #  subnet: 255.255.255.0

globals:
  - id: fast_forward_release_time
    type: unsigned long
    restore_value: no
    initial_value: '0'
  - id: fast_forward_long_press_time
    type: unsigned long
    restore_value: no
    initial_value: '0'
  - id: fast_forward_seek_type
    type: int
    initial_value: '0'
    restore_value: no

  - id: selected_track
    type: unsigned long
    restore_value: no
    initial_value: '0'
  - id: selected_time
    type: int
    initial_value: '7'
    restore_value: no



script:
  - id: set_seek_type
    parameters:
      seek_type: int
    then:
      lambda: |-
        if (id(fast_forward_seek_type) == 0) {
          id(fast_forward_seek_type) = seek_type;
        }
  - id: set_seek_value
    parameters: 
      direction: int
      press_duration: int
    then:
    - lambda: |-
        if (id(fast_forward_seek_type) == 1) {
          id(selected_time)=0;
          id(selected_track)+= 1 * direction;
        } else {
          uint8_t seek_rate = 5;
          ESP_LOGI("press","check press duration: %d",  press_duration);
          if (press_duration > 0) {
            ESP_LOGI("press","Press duration > 0: %d - %d",  press_duration, millis() - press_duration);
            if (millis() - press_duration > 10000) {
              seek_rate = 30;
            } else {
              if (millis() - press_duration > 5000) {
                seek_rate = 10;
              }
            }

          }
          id(selected_time) = id(selected_time) + (seek_rate * direction) - (id(selected_time) % seek_rate);
        }
    - logger.log:
        format: "Track value: %02d - Seek value: %02d"
        args: [ 'id(selected_track)', 'id(selected_time)' ]

binary_sensor:
  # button does the following:
  # short click - stop a timer
  # if no timer then restart either microwakeword or voice assistant continuous
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button
    disabled_by_default: true
    entity_category: diagnostic
    id: echo_button
#    filters:
#      - delayed_off: 1000ms
    on_release:
      then:
        - lambda: |-
            id(fast_forward_release_time) = millis();
        - wait_until:
            condition:
              binary_sensor.is_on: echo_button
            timeout: 1s
        - if:
            condition:
              lambda: |-
                return  (millis() - id(fast_forward_release_time)) > 1000;
            then:
            - logger.log:
                format: "Seek to track: %02d - position: %02d"
                args: [ 'id(selected_track)', 'id(selected_time)' ]
            - globals.set:
                id: fast_forward_seek_type
                value: '0'


    on_multi_click:
    - timing:
        - ON for at most 500ms
      then:
        - logger.log: "Normal click"
        - script.execute:
            id: set_seek_type
            seek_type: '1'
        - script.wait: set_seek_type
        - script.execute:
            id: set_seek_value
            direction: '1'
            press_duration: 0

    - timing:
        - ON for at least 1000ms
      then:
        - logger.log: "Long click"
        - script.execute:
            id: set_seek_type
            seek_type: '2'
        - script.wait: set_seek_type
        - lambda: |-
            id(fast_forward_long_press_time) = millis();
        - while:
            condition:
              binary_sensor.is_on: echo_button
            then:
            - logger.log: "Still executing"
            - script.execute:
                id: set_seek_value
                direction: '1'
                press_duration: !lambda "return id(fast_forward_long_press_time);"
            - delay: 500ms


button:
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
  - platform: restart
    name: "${friendly_name} Restart"


# script:
