# Basic Config
substitutions:
  friendly_name: Condizionatore camere
  device_name: condizionatore_camere

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  # optional
#  on_boot:
#    then:
#      - switch.turn_on: relay

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    

wifi:
  ssid: !secret wifi_dmz_ssid
  password: !secret wifi_dmz_password
  use_address: 192.168.2.108
#  ap:
#    ssid: ${device_name}
#    password: "12345678"
  on_connect:
    then:
      - light.turn_on: wifi_status_led
  on_disconnect:
    then:
      - light.turn_off: wifi_status_led

#captive_portal:

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api_key
    
ota:
  password: !secret ota_pwd_sec
  platform: esphome

#optional
web_server:
  port: 80

uart:
-  rx_pin: GPIO16
   baud_rate: 4800
   parity: EVEN
   id: current_sensor

sensor:
  - platform: cse7766
    uart_id: current_sensor
    current:
      name: ${friendly_name} Current
      id: a_sensor
      filters:
#        - throttle_average: 30s
        - throttle_average: 5s
    voltage:
      name: ${friendly_name} Voltage
      id: v_sensor
      filters:
#        - throttle: 30s
        - throttle: 5s
    power:
      name: ${friendly_name} Power
      id: w_sensor
      filters:
#        - throttle_average: 30s
        - throttle_average: 5s
    energy:
      name: ${friendly_name} Energy
      id: wh_sensor
      filters:
#        - throttle_average: 30s
        - throttle_average: 5s

#  - platform: template
#    name: $friendly_name ESP32 Internal Temp
#    device_class: temperature
#    unit_of_measurement: °C
#    id: esp32_temp
#    lambda: return temperatureRead();
#    update_interval: 600s

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 600s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

output:
  - platform: ledc
    id: led
    pin:
      number: GPIO18
      inverted: True

light:
  - platform: monochromatic
    id: switch_led
    output: led
    internal: True
    default_transition_length: 0s
  - platform: status_led
    id: wifi_status_led
    internal: True
    pin:
      number: GPIO05
      inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${friendly_name} - Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${friendly_name} - Relay Switch"
    pin: GPIO13
    id: relay
    on_turn_on:
      then:
        - light.turn_on: switch_led
    on_turn_off:
      then:
        - light.turn_off: switch_led