substitutions:
  name: garage-assistant
  friendly_name: Garage Assistant

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0

esp32:
  board: m5stack-atom
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: 6.0.2
    advanced:
      sram1_as_iram: true
      
logger:
  level: DEBUG

  
api:

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_pwd_sec

wifi:
  networks:
#  - ssid: !secret wifi_dmz_ssid
#    password: !secret wifi_dmz_password
#  use_address: 192.168.2.186
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
##  use_address: 192.168.1.99
#  ap:

#captive_portal:

button:
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO33
    i2s_bclk_pin: GPIO19

microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: GPIO23
    adc_type: external
    pdm: true
    sample_rate: 16000
    correct_dc_offset: true

speaker:
  - platform: i2s_audio
    id: echo_speaker
    i2s_dout_pin: GPIO22
    dac_type: external
    bits_per_sample: 16bit
#    sample_rate: 44100
    channel: mono  # The Echo has poor playback audio quality when using mon audio
    buffer_duration: 60ms
#    buffer_duration: 60ms

audio_file:
  file: https://github.com/esphome/wake-word-voice-assistants/raw/main/sounds/timer_finished.wav
  id: timer_finished_wave_file

sendspin:
  
  
media_source:
  - platform: audio_http
    id: source_http
    buffer_size: 5000
  - platform: audio_file
    id: source_file
  - platform: sendspin
    id: source_sendspin
    buffer_size: 30000

media_player:
  - platform: sendspin
    name: "Sendspin Group"
    
  - platform: speaker_source
    name: None
    id: echo_media_player
    announcement_pipeline:
      speaker: echo_speaker
      format: MP3
      sample_rate: 44100
      sources:
        - source_http
        - source_file
        - source_sendspin
#    media_pipeline: 
#      speaker: echo_speaker
#      sources:
#        - source_http
#        - source_file
    volume_min: 0.8

light:
  - platform: esp32_rmt_led_strip
    id: led
    name: None
    disabled_by_default: true
    entity_category: config
    pin: GPIO27
    default_transition_length: 0s
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%
