esphome:
  name: lettorecd
  friendly_name: Lettore CD
  
esp8266:
  board: esp12e

# Enable logging
logger:
  level: DEBUG
  baud_rate: 115200

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_pwd
  id: my_ota
  platform: esphome

wifi:
  ssid: !secret wifi_dmz_ssid
  password: !secret wifi_dmz_password
  use_address: 192.168.2.17

# mqtt:
#   id: mqtt_client
#   broker: !secret mqtt_server
#   username: !secret mqtt_user
#   password: !secret mqtt_pwd
#   discovery: false
#   client_id: ${name}
# #  log_topic: null

external_components:
  - source: /config/components/
    components: [ atapi ]

captive_portal:
    
i2c:
  scan: False
  frequency: 400kHz
#  sda: GPIO5
#  scl: GPIO4

font:
#   - file: "gfonts://Roboto"
    # id: roboto_20
    # size: 20
  - file: 'fonts/LiberationMono-Regular.ttf'
    id: font_header
    size: 14

  - file: 'fonts/LiberationMono-Regular.ttf'
    id: font_body
    size: 24

    # webfonts from https://pictogrammers.com/
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: md_state_icons
    size: 40
    glyphs:
      - "\U000F01D1" # disc-alert
      - "\U000F05EE" # disc
      - "\U000F040A" # play
      - "\U000F03E4" # pause
      - "\U000F04DB" # stop
      - "\U000F01EA" # eject
      - "\U000F0453" # loading
      - "\U000F0028" # alert
#      - "\U000" # 
    
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    id: lcd_display
    # show_test_card: true
    lambda: |-
      switch (id(cd_reader).get_disc_state()) {
        case 0:
          it.print(0, 0, id(font_header), "No disc");
          break;
        case 1:
          it.printf(0, 0, id(font_header), "%02d:%02d",id(cd_reader).get_total_time() / 60, id(cd_reader).get_total_time() % 60 );
          if (id(cd_reader).get_status() > 1) {
            it.printf(it.get_width(), 0, id(font_header),TextAlign::TOP_RIGHT,"%02d:%02d",id(cd_reader).get_current_time() / 60, id(cd_reader).get_current_time() % 60);
          }
          break;
        case 2:
          it.print(0, 0, id(font_header), "Tray opened");
          break;
      }

      it.line(0, 20, it.get_width(), 20);

      it.printf(0, 22, id(md_state_icons), TextAlign::TOP_LEFT,"\U000F01D1");

      if (id(cd_reader).get_disc_state() == 1) {
        it.printf(50, 28, id(font_body), "%02d/%02d", (id(cd_reader).get_status() > 1)?id(cd_reader).get_current_track():0,id(cd_reader).get_tracks() );
        if (id(cd_reader).get_status() > 1) {
          it.printf(65, 48, id(font_header),TextAlign::TOP_LEFT,"%02d:%02d",id(cd_reader).get_current_track_time() / 60, id(cd_reader).get_current_track_time() % 60);
        } else {
          it.print(65, 48, id(font_header),TextAlign::TOP_LEFT,"00:00");
        }

      } else {
        it.print(50, 28, id(font_body), "--/--");
      }
      

atapi:
  id: cd_reader
  on_error:
    - component.update: lcd_display
  on_lock:
    - component.update: lcd_display
  on_update:
    - component.update: lcd_display
  on_toc:
    - component.update: lcd_display
  on_state:
    - component.update: lcd_display
    - light.control:
        id: light_led
        state: !lambda |-
          return x;
          
#  frequency: 500kHz


binary_sensor:
  - platform: gpio
    internal: True
    name: "Play Pause"
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lambda: |-
          id(cd_reader).enqueue_play();
  - platform: gpio
    internal: True
    name: "Stop Eject"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lambda: |-
          id(cd_reader).enqueue_stop();
  - platform: gpio
    internal: True
    name: "Next track"
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lambda: |-
          id(cd_reader).enqueue_next();
  - platform: gpio
    internal: True
    name: "Previous track"
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - lambda: |-
          id(cd_reader).enqueue_previous();

output:
  - platform: esp8266_pwm
    pin: GPIO13
    id: pwm_led

light:
  - platform: monochromatic
    name: "Device led"
    output: pwm_led
    internal: True
    id: light_led
    restore_mode: ALWAYS_ON
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.1s
          update_interval: 0.1s
          min_brightness: 0%
          max_brightness: 70%
      - pulse:
          name: "Slow Pulse"
          transition_length: 5s
          update_interval: 5s
          min_brightness: 20%
          max_brightness: 50%
      - pulse:
          name: "Blink"
          transition_length: 0s
          update_interval: 0.3s
          min_brightness: 0%
          max_brightness: 100%

# remote_receiver:
#   pin: 
#     number: GPIO12
#     inverted: True
#   dump: all

button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: restart
    name: "Restart"
  - platform: template
    name: Reset IDE Device
    id: reset_device
    on_press:
      - logger.log: Reset device request
      - lambda: |-
          // id(cd_reader).reset_all();
          id(cd_reader).enqueue_reset();
  - platform: template
    name: Play
    id: play
    on_press:
      - logger.log: Play request
      - lambda: |-
          id(cd_reader).enqueue_play();
  - platform: template
    name: Stop
    id: stop
    on_press:
      - logger.log: Stop request
      - lambda: |-
          id(cd_reader).enqueue_stop();
  - platform: template
    name: Eject
    id: eject
    on_press:
      - logger.log: Eject request
      - lambda: |-
          id(cd_reader).enqueue_eject();
  - platform: template
    name: Load
    id: load
    on_press:
      - logger.log: Load request
      - lambda: |-
          id(cd_reader).enqueue_load();
  - platform: template
    name: Pause
    id: pause_
    on_press:
      - logger.log: Pause request
      - lambda: |-
          id(cd_reader).enqueue_pause();
  - platform: template
    name: Resume
    id: resume
    on_press:
      - logger.log: Resume request
      - lambda: |-
          id(cd_reader).enqueue_resume();
  - platform: template
    name: Stop Disc
    id: stop_disc
    on_press:
      - logger.log: Stop disc request
      - lambda: |-
          id(cd_reader).enqueue_stop_disc();
  - platform: template
    name: Next
    id: next_track
    on_press:
      - logger.log: Next track request
      - lambda: |-
          id(cd_reader).enqueue_next();
  - platform: template
    name: Previous
    id: prev_track
    on_press:
      - logger.log: Previous track request
      - lambda: |-
          id(cd_reader).enqueue_previous();
  - platform: template
    name: Restart track
    id: restart_track
    on_press:
      - logger.log: Restart track request
      - lambda: |-
          id(cd_reader).enqueue_restart_track();
