# Basic Config
substitutions:
  friendly_name: test-media-player
  device_name: test-media-player

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  libraries:
#    - SBCDecoder=https://github.com/pschatzmann/arduino-libsbc
#    - AACDecoder=https://github.com/pschatzmann/arduino-libhelix
#    - AudioTools=https://github.com/pschatzmann/arduino-audio-tools
    - BluetoothA2DPSink=https://github.com/pschatzmann/ESP32-A2DP
  platformio_options:
    build_flags: 
      - -DUSE_DEFAULT_STDLIB
      - -DUSE_IDF_LOGGER
      - -DEXIT_ON_STOP
#  includes:
#    - includes/advanced_bt_component.h

psram:
  mode: quad
  speed: 80MHZ
  
mdns:
  disabled: false

  
esp32:
  board: esp-wrover-kit
  partitions: partition_layouts/huge_app_esp32.csv
  
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_ENABLED: y
      CONFIG_BT_BLE_ENABLED: n
      CONFIG_BT_GATTS_ENABLE: n
      CONFIG_BT_CLASSIC_ENABLED: y
      CONFIG_BT_A2DP_ENABLE: y
      CONFIG_BT_SPP_ENABLED: y
      CONFIG_BT_BLUEDROID_ENABLED: y
      CONFIG_BT_NIMBLE_ENABLED: n
      CONFIG_BTDM_CTRL_MODE_BTDM: y
#    version: 6.0.2
    version: 6.1-beta1
    advanced:
      sram1_as_iram: true

  cpu_frequency: 240MHZ
wifi:
  power_save_mode: none
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_btm: true
  enable_rrm: true
  manual_ip:
    static_ip: 192.168.1.102
    subnet: 255.255.255.0
    gateway: 192.168.1.1
    
logger:
  hardware_uart: UART0
  level: DEBUG
  baud_rate: 115200

api:

ota:
  platform: esphome

external_components:
  - source: /config/components/
    components: [ a2dp_sink ]
  - source: github://pr#3552  # DAC support https://github.com/esphome/esphome/pull/3552
    components: [es8388]
    refresh: 0s

sendspin:
#  task_stack_in_psram: false

a2dp_sink:
  name: test
  
media_source:
  - platform: audio_http
    id: http_source
    buffer_size: 1000000
#    task_stack_in_psram: true
  - platform: sendspin
#    fixed_delay: 10ms
    id: sendspin_media_source
#    task_stack_in_psram: true
#    decode_memory: internal
#    buffer_size: 2000000
    static_delay_adjustable: true
  - platform: a2dp_sink
    id: bluetooth

voice_assistant:
  microphone: luxe_microphone
  media_player: external_media_player
  on_start:
    - light.turn_on:
        id: top_led
        blue: 100%
        red: 0%
        green: 0%
        effect: none
  on_tts_start:
    - light.turn_on:
        id: top_led
        blue: 60%
        red: 20%
        green: 20%
        effect: none
  on_tts_end:
    then:
      - media_player.play_media:
          media_url: !lambda return x;
          id: external_media_player
      - light.turn_on:
          id: top_led
          blue: 60%
          red: 20%
          green: 20%
          effect: pulse
  on_end:
    then:
      - delay: 1s
      - wait_until:
          condition:
            not:
              media_player.is_playing: external_media_player
      - light.turn_off: top_led
  on_error:
    - light.turn_on:
        id: top_led
        blue: 0%
        red: 100%
        green: 0%
        effect: none
    - delay: 1s
    - light.turn_off: top_led
      
media_player:
  - platform: sendspin
    id: sendspin_group_media_player
    
  - platform: speaker_source
    id: external_media_player
    name: Media Player
    media_pipeline:
      format: FLAC
      num_channels: 2
      sample_rate: 48000
      speaker: luxe_speaker
      sources:
        - sendspin_media_source
        - bluetooth
        - http_source
  
#optional
#web_server:
#  port: 80

i2c:
  - id: i2c_bus
    sda: GPIO18
    scl: GPIO23
    
#audio_dac:
# - platform: es8388


es8388:
  
i2s_audio:
#  - id: i2s_spdif
    
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO5

microphone:
  - platform: i2s_audio
    id: luxe_microphone
    i2s_din_pin: GPIO35
    adc_type: external
    pdm: false
    
speaker:
#  - platform: i2s_audio
#    id: spdif_speaker
#    dac_type: external
#    i2s_audio_id: i2s_spdif
#    i2s_dout_pin: GPIO23
#    spdif_mode: true
#    use_apll: true
#    sample_rate: 48000
#    channel: stereo
#    timeout: never
#    buffer_duration: 2s
  - platform: i2s_audio
    id: luxe_speaker
    i2s_audio_id: i2s_audio_bus
    dac_type: external
    i2s_dout_pin: GPIO26
    channel: stereo
#    sample_rate: 44100
  
sensor:

#  - platform: wifi_signal
#    name: "WiFi Signal"
#    update_interval: 600s
  - platform: sendspin
    type: track
    name: traccia
    id: sensor_sendspin_1
  - platform: a2dp_sink
    type: tracknum
    id: "btTrackNr"
    name: "Track Number"
  - platform: a2dp_sink
    type: playingtime
    id: "btPlayingTime"
    name: "Playing Time"
  - platform: a2dp_sink
    type: num_tracks
    id: "btNumTracks"
    name: "Total Tracks"
  - platform: a2dp_sink
    type: trackposition
    id: "btTrackPos"
    name: "Track Position"
  - platform: a2dp_sink
    type: rssi
    id: "btRSSI"
    name: "RSSI"
  - platform: adc
    id: battery_sensor
    pin: GPIO33
    name: Battery
    icon: "mdi:battery-outline"
    device_class: voltage
    state_class: measurement
    entity_category: diagnostic
    unit_of_measurement: V
    update_interval: 15s
    accuracy_decimals: 3
    attenuation: 11db
    raw: true
    filters:
      - multiply: 0.00173913  # 2300 -> 4, for attenuation 11db, based on Olivier's code
      - exponential_moving_average:
          alpha: 0.2
          send_every: 2
      - delta: 0.002
        
text_sensor:
  - platform: a2dp_sink
    id: "bt_artist"
    type: "artist"
    name: "Artist"
  - platform: a2dp_sink
    id: "bt_album"
    type: "album"
    name: "Album"
  - platform: a2dp_sink
    id: "bt_titlea"
    type: "title"
    name: "Titlea"
  - platform: a2dp_sink
    id: "bt_peername"
    type: "peername"
    name: "Peer name"
  - platform: a2dp_sink
    id: "bt_peeraddr"
    type: "peeraddr"
    name: "Peer address"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
  - platform: sendspin
    type: title
    name: titolo
    id: text_sensor_sendspin_1
  - platform: sendspin
    type: artist
    name: artista
    id: text_sensor_sendspin_2

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO19
      inverted: true
      mode:
        input: true
        pullup: true
    name: Volume Up
    id: volume_up
    on_click:
      then:
        - media_player.volume_up: external_media_player
  - platform: gpio
    pin:
      number: GPIO32
      inverted: true
      mode:
        input: true
        pullup: true
    name: Volume Down
    id: volume_down
    on_click:
      then:
        - media_player.volume_down: external_media_player
  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    name: Action
    id: action_button
    on_multi_click:
      - timing:
          - ON FOR AT MOST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - media_player.toggle: external_media_player
      - timing:
          - ON FOR AT LEAST 350ms
        then:
          - voice_assistant.start:
      - timing:
          - ON FOR AT LEAST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - voice_assistant.stop:

switch:
  - platform: a2dp_sink
    type: connection
    name: "Bluetooth connection"
    id: "btConnection"
    restore_mode: ALWAYS_OFF
    
  - platform: a2dp_sink
    type: bluetooth
    name: "Bluetooth state"
    id: "btState"
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: amplifier
    id: amplifier_enable
    pin:
      number: GPIO21
      inverted: true
    restore_mode: ALWAYS_OFF
    
button:
  - platform: template
    name: next
    on_press:
      - then:
          - logger.log:
              level: INFO
              format: Next
          - media_player.next: external_media_player
  - platform: template
    name: previous
    on_press:
      - then:
          - media_player.previous: external_media_player
            
  - platform: restart
    name: "restart"
    id: button_restart_1


light:
  - platform: esp32_rmt_led_strip
    name: None
    id: top_led
    pin: GPIO22
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    gamma_correct: 2.8
    effects:
      - pulse:
          transition_length: 250ms
          update_interval: 250ms