# Basic Config
substitutions:
  friendly_name: test-media-player
  device_name: test-media-player

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

psram:
  mode: quad
  speed: 80MHZ
  
mdns:
  disabled: false
  
esp32:
  variant: esp32
  framework:
    type: esp-idf
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
logger:

api:

ota:
  platform: esphome
  
sendspin:
  task_stack_in_psram: false

media_source:
  - platform: audio_http
    id: http_source
  - platform: sendspin
    id: sendspin_media_source

media_player:
  - platform: sendspin
    id: sendspin_group_media_player
  - platform: speaker_source
    id: external_media_player
    name: Media Player
    media_pipeline:
      speaker: spdif_speaker
      sources:
        - sendspin_media_source
        - http_source
  
#optional
web_server:
  port: 80

i2s_audio:
  - id: i2s_output

speaker:
  - platform: i2s_audio
    id: spdif_speaker
    dac_type: external
    i2s_audio_id: i2s_output
    i2s_dout_pin: GPIO25
    spdif_mode: true
    use_apll: true
    sample_rate: 48000
    channel: stereo
    timeout: never
    buffer_duration: 2000ms
  
sensor:

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 600s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

button:
  - platform: restart
    id: button_restart_1
