# Basic Config
substitutions:
  friendly_name: Player HiFi
  device_name: player-hifi

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

psram:
  mode: quad
  speed: 80MHZ
  
mdns:
  disabled: false

  
esp32:
  board: esp-wrover-kit
#  partitions: partition_layouts/huge_app_esp32.csv
  
  framework:
    type: esp-idf
    version: 6.0.2
#    version: 6.1-beta1
    advanced:
      sram1_as_iram: true
  cpu_frequency: 240MHZ

wifi:
  power_save_mode: none
  ssid: !secret wifi_dmz_ssid
  password: !secret wifi_dmz_password
    
logger:
  hardware_uart: UART0
  level: DEBUG
  baud_rate: 115200

api:

ota:
  platform: esphome

external_components:
  - source: github://PxPert/a2dp_sink@master
    components: [ a2dp_sink ]
    refresh: never

packages:
  device_base: !include includes/dev_museluxe_base.yaml
#  device_ext: !include includes/dev_museluxe_voice_extensions.yaml
  
sendspin:

a2dp_sink:
  name: test
  minimal_bluetooth: true
          
media_source:
  - platform: sendspin
    id: sendspin_media_source
    static_delay_adjustable: true
  - platform: a2dp_sink
    id: bluetooth
  
media_player:
  - platform: sendspin
    id: sendspin_group_media_player
    
  - platform: speaker_source
    id: external_media_player
    name: Media Player
    media_pipeline:
      format: FLAC
      num_channels: 2
      sample_rate: 48000
      speaker: luxe_speaker
      sources:
        - sendspin_media_source
        - bluetooth
  
speaker:
  - platform: i2s_audio
    dac_type: external
    i2s_dout_pin: GPIOXX
    

number:
  - platform: a2dp_sink
    name: "Volume"

switch:
  - platform: a2dp_sink
    type: connection
    name: "Bluetooth connection"
    id: "btConnection"
    restore_mode: ALWAYS_OFF

  - platform: a2dp_sink
    type: bluetooth
    name: "Bluetooth state"
    id: "btState"
    restore_mode: RESTORE_DEFAULT_OFF

    
button:
  - platform: template
    name: next
    on_press:
      - then:
          - media_player.next: external_media_player
  - platform: template
    name: previous
    on_press:
      - then:
          - media_player.previous: external_media_player
            
  - platform: restart
    name: "restart"
    id: button_restart_1

