substitutions:
  friendly_name: Player HiFi
  device_name: player-hifi

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

psram:
  mode: quad
  speed: 120MHZ
#  ignore_not_found: false
  
mdns:
  disabled: false
  
esp32:
  board: esp-wrover-kit
#  partitions: partition_layouts/huge_app_esp32.csv
  
  framework:
    type: esp-idf
    version: 6.0.2
#    version: 6.1-beta1
    advanced:
      sram1_as_iram: true
  cpu_frequency: 240MHZ

wifi:
  power_save_mode: none
  ssid: !secret wifi_dmz_ssid
  password: !secret wifi_dmz_password
    
logger:
  hardware_uart: UART0
  level: WARN
  
  baud_rate: 0
  task_log_buffer_size: 0
  tx_buffer_size: 160

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_pwd_sec

external_components:
  - source: github://PxPert/a2dp_sink@master
    components: [ a2dp_sink ]
#    refresh: never
  
sendspin:

a2dp_sink:
  name: HiFiPlayer
  minimal_bluetooth: true
          
i2s_audio:
  - id: i2s_spdif
    
speaker:
  - platform: i2s_audio
    id: speaker_spdif
    dac_type: external
    channel: stereo
    use_apll: true
    sample_rate: 44100
    i2s_dout_pin: GPIO32
    spdif_mode: true
    buffer_duration: 100ms
  - platform: resampler
    output_speaker: speaker_spdif
    sample_rate: 44100
    task_stack_in_psram: true
    id: speaker_resampler
    buffer_duration: 100ms
    

media_source:
  - platform: sendspin
    id: media_source_sendspin
    static_delay_adjustable: true
  - platform: a2dp_sink
    id: media_source_bluetooth
    
media_player:    
  - platform: speaker_source
    id: external_media_player
    name: Media Player
    media_pipeline:
      format: FLAC
      num_channels: 2
      sample_rate: 44100
      speaker: speaker_resampler
      sources:
        - media_source_sendspin
        - media_source_bluetooth
    on_state:
      - then: 
        - lambda: |-
            ESP_LOGW("TEST","TEST player state %d", id(external_media_player).state);
            ESP_LOGW("TEST","TEST bluetooth state %d", id(media_source_bluetooth).get_state());
            ESP_LOGW("TEST","TEST sendspin state %d", id(media_source_sendspin).get_state());


          
font:
#  - file: "fonts/Roboto-Regular.ttf"
#    id: font_regular
#    size: 16
#    glyphs: "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ.-,+/°:() "
  - file: "fonts/Roboto-Light.ttf"
    id: font_light
    size: 24
    glyphs: "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ.-,+/°:() "
#  - file: "fonts/Roboto-Condensed.ttf"
#    id: font_condensed
#    size: 16
#    glyphs: "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ.-,+/°:() "
    
#  - file: "fonts/materialdesignicons-webfont.ttf"
#    id: font_mdi
#    size: 24
#    glyphs: !lambda return {};

number:
  - platform: a2dp_sink
    name: "Bluetooth Volume"

    
switch:
  - platform: a2dp_sink
    type: connection
    name: "Bluetooth connection"
    id: "btConnection"
    restore_mode: ALWAYS_OFF

  - platform: a2dp_sink
    type: bluetooth
    name: "Bluetooth state"
    id: "btState"
    restore_mode: RESTORE_DEFAULT_OFF

    
button:
  - platform: template
    name: next
    on_press:
      - then:
          - media_player.next: external_media_player
  - platform: template
    name: previous
    on_press:
      - then:
          - media_player.previous: external_media_player
            
  - platform: restart
    name: "restart"
    id: button_restart_1

# --- I2C Bus ---
i2c:
  sda: GPIO19
  scl: GPIO18
  frequency: 10kHz
  scan: false

# --- Display OLED SSD1306 ---
display:
  - platform: ssd1306_i2c
    model: SSD1306_128X64
    address: 0x3C
    lambda: |-
      it.rectangle(0, 0, 128, 17);
      it.printf(64, 32, id(font_light), TextAlign::CENTER, "Player HiFi");

    flip_x: true
    flip_y: true

# --- Pulsanti GPIO ---
binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
    name: "Pulsante Avanti"
    on_press:
      then:
        - logger.log:
            level: INFO
            format: "Pulsante Avanti premuto"

  - platform: gpio
    internal: true
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
    name: "Pulsante Indietro"
    on_press:
      then:
        - logger.log:
            level: INFO
            format: "Pulsante Indietro premuto"

  - platform: gpio
    internal: true
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    name: "Pulsante Play-Stop"
    on_press:
      then:
        - logger.log:
            level: INFO
            format: "Pulsante Play/Stop premuto"

