substitutions:
  friendly_name: Portable speaker
  device_name: portable-speaker
  
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp-wrover-kit
  flash_frequency: 80MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_WIFI_RX_IRAM_OPT: "y"
      CONFIG_ESP_WIFI_IRAM_OPT: "y"
      CONFIG_ESP_WIFI_EXTRA_IRAM_OPT: "y"
      CONFIG_LWIP_IRAM_OPTIMIZATION: "y"
    advanced:
      sram1_as_iram: true
      
psram:
  mode: quad
  speed: 80MHZ
  ignore_not_found: true
  
logger:
  hardware_uart: UART0
  baud_rate: 115200
  
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_pwd_sec

i2c:
  - id: i2c_bus
    sda: GPIO18
    scl: GPIO23

wifi:
  ssid: !secret wifi_dmz_ssid
  password: !secret wifi_dmz_password

external_components:
  - source: github://pr#3552  # DAC support https://github.com/esphome/esphome/pull/3552
    components: [es8388]
    refresh: 0s

es8388:

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO5

speaker:
  - platform: i2s_audio
    id: luxe_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO26
    dac_type: external
    channel: stereo
    buffer_duration: 100ms
#    audio_dac: es8388_dac # <<< adding this line breaks volume control in MA.
  - platform: mixer
    id: mixing_speaker
    output_speaker: luxe_speaker
    num_channels: 2
    task_stack_in_psram: false
    source_speakers:
      - id: announcement_mixing_input
      - id: media_mixing_input

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

microphone:
  - platform: i2s_audio
    id: luxe_microphone
    i2s_audio_id: i2s_audio_bus
    sample_rate: 16000
    i2s_din_pin: GPIO35
    bits_per_sample: 16bit
    channel: stereo
    adc_type: external  

sendspin:
  id: sendspin_hub
  task_stack_in_psram: false

switch:
  - platform: gpio
    id: amplifier_enable
    pin:
      number: GPIO21
#      inverted: true
    restore_mode: ALWAYS_ON
    internal: true

light:
  - platform: esp32_rmt_led_strip
    name: None
    id: top_led
    pin: GPIO22
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    gamma_correct: 2.8
    effects:
      - pulse:
          transition_length: 250ms
          update_interval: 250ms

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset

#audio_file:
#  - id: ready_sound
#    file: https://github.com/RealDeco/xiaozhi-esphome/raw/main/sounds/${startup_sound_file}.flac
    
media_source:
#  - platform: audio_file
#    id: audio_file_announcement_source
  - platform: audio_http
    id: http_announcement_source
  - platform: audio_http
    id: http_media_source
  - platform: sendspin
    id: sendspin_media_source
    decode_memory: internal

media_player:
  - platform: speaker_source
    id: external_media_player
    name: none

    announcement_pipeline:
      format: FLAC
      num_channels: 1
      sample_rate: 48000
      speaker: luxe_speaker
      sources:
        - http_announcement_source
    media_pipeline:
      format: FLAC
      num_channels: 2
      sample_rate: 48000
      speaker: media_resampling_speaker
      sources:
        - http_media_source
        - sendspin_media_source
    volume_increment: 0.05
    volume_min: 0.4
    volume_max: 0.9

      
voice_assistant:
  id: va
  microphone:
    - microphone: luxe_microphone
  media_player: external_media_player
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0

  on_end:
    - wait_until:
        condition:
          media_player.is_announcing:
            id: external_media_player
        timeout: 0.5s
    - wait_until:
        - and:
            - not:
                media_player.is_announcing:
                  id: external_media_player
            - not:
                speaker.is_playing:
                  id: luxe_speaker

sensor:
  - platform: adc
    id: battery_sensor
    pin: GPIO33
    name: Battery
    icon: "mdi:battery-outline"
    device_class: voltage
    state_class: measurement
    entity_category: diagnostic
    unit_of_measurement: V
    update_interval: 15s
    accuracy_decimals: 3
    attenuation: 11db
    raw: true
    filters:
      - multiply: 0.00173913  # 2300 -> 4, for attenuation 11db, based on Olivier's code
      - exponential_moving_average:
          alpha: 0.2
          send_every: 2
      - delta: 0.002

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO19
      inverted: true
      mode:
        input: true
        pullup: true
    name: Volume Up
    id: volume_up
    on_click:
      - media_player.volume_up:
          id: external_media_player
  - platform: gpio
    pin:
      number: GPIO32
      inverted: true
      mode:
        input: true
        pullup: true
    name: Volume Down
    id: volume_down
    on_click:
      - media_player.volume_down:
          id: external_media_player
  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    name: Action
    id: action_button
    on_multi_click:
      - timing:
          - ON FOR AT MOST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - media_player.toggle:
              id: external_media_player
      - timing:
          - ON FOR AT LEAST 350ms
        then:
          - voice_assistant.start:
      - timing:
          - ON FOR AT LEAST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - voice_assistant.stop:

