esphome:
  name: stazione-meteo
  friendly_name: Stazione meteo

  devices:
    - id: meteo_station
      name: "Stazione meteo"
    - id: leds_cucinotto
      name: "Luci cucinotto"

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG

preferences:
  flash_write_interval: 6h

mdns:
  disabled: True

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

wifi:
  ssid: !secret wifi_dmz_ssid
  password: !secret wifi_dmz_password
  use_address: 192.168.2.12
#  manual_ip:
#    static_ip: 192.168.2.12
#    gateway: 192.168.2.1
#    subnet: 255.255.255.0
#    dns1: 192.168.2.1

external_components:
  - source: /config/components/
    components: [ bresser5in1_cc1101, ansluta_cc2500 ]
#  - source: github://PxPert/ikea-ansluta-esphome

ota:
  platform: esphome
  password: !secret ota_pwd_sec
  on_begin:
    - lambda: id(weather_station)->stopInterrupts();

spi:
  # these are the default SPI pins to use on ESP8266
  clk_pin: SCK   # CC1001 pin 5
  mosi_pin: MOSI  # CC1001 pin 6
  miso_pin: MISO  # CC1001 pin 7

ansluta_cc2500:
  spi_mode: 0
  data_rate: 4MHz
  cs_pin: 16
  on_remote_click:
    debounce: 100
    then:
      lambda: |-
        ESP_LOGD("ansluta-yaml","Button clicked! %d", x);

light:
  - platform: ansluta_cc2500
    device_id: leds_cucinotto
    name: "Cucinotto"

bresser5in1_cc1101:
  spi_mode: 0
  data_rate: 4MHz
  filter_station_id: 185

  id: weather_station

  cs_pin: 5 # CC1101 pin 4
  rx_pin:
    number: 4 # This is CC1101 GDO0 pin 3
    allow_other_uses: false
    mode:
      input: true
      pullup: true
  on_state:
    lambda: |-
      ESP_LOGD("bresser5in1","NEW READ! Temp: %.2f", x->temperature);

sensor:
  - platform: bresser5in1_cc1101
    temperature:
      device_id: meteo_station
      name: "Temperature"
    station_id:
      device_id: meteo_station
      name: "Station ID"
    humidity:
      device_id: meteo_station
      name: "Humidity"
    wind_direction_degrees:
      device_id: meteo_station
      name: "Wind direction"
    wind_gusts_speed:
      device_id: meteo_station
      name: "Wind gust speed"
    wind_speed:
      device_id: meteo_station
      name: "Wind speed"
    rain_level:
      device_id: meteo_station
      name: "Rain level"
    rssi:
      device_id: meteo_station
      name: "RSSI"

binary_sensor:
  - platform: bresser5in1_cc1101
    battery_low:
      device_id: meteo_station
      name: "Battery Low"

#switch:
#  - platform: gpio
#    pin: GPIO16
#    name: "CC2500 CS"

button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: restart
    name: "Restart"
  - platform: template
    device_id: meteo_station
    name: Reset CC1101
    id: reset_cc1101
    on_press:
      - lambda: |-
          id(weather_station).radioInit();