esphome:
  name: stazione-meteo
  friendly_name: Stazione meteo
  platformio_options:
    build_flags: -DRADIOLIB_EXCLUDE_LORAWAN=true -DRADIOLIB_EXCLUDE_PAGER=true
esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG

preferences:
  flash_write_interval: 6h

mdns:
  disabled: True

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

wifi:
  ssid: !secret wifi_dmz_ssid
  password: !secret wifi_dmz_password
  use_address: 192.168.2.12
#  manual_ip:
#    static_ip: 192.168.2.12
#    gateway: 192.168.2.1
#    subnet: 255.255.255.0
#    dns1: 192.168.2.1

external_components:
  - source: /config/components/
    components: [ bresser5in1_cc1101 ]
# packages:
#   cc1101_controls: !include includes/cc1101-controls.yaml

ota:
  platform: esphome
  password: !secret ota_pwd_sec
  on_begin:
    - lambda: noInterrupts();


spi:
  # these are the default SPI pins to use on ESP8266
  clk_pin: SCK   # CC1001 pin 5
  mosi_pin: MOSI  # CC1001 pin 6
  miso_pin: MISO  # CC1001 pin 7

bresser5in1_cc1101:
  spi_mode: 0
  data_rate: 4MHz
  id: weather_station

  cs_pin: 5 # CC1101 pin 4
  rx_pin:
    number: 4 # This is CC1101 GDO0 pin 3
    allow_other_uses: false
    mode:
      input: true
      pullup: true
  on_state:
    lambda: |-
      ESP_LOGD("bresser5in1","NEW READ! Temp: %.2f", x->temperature);

sensor:
 - platform: bresser5in1_cc1101
   temperature:
     name: "Temperature"
   station_id:
     name: "Station ID"
   humidity:
     name: "Humidity"
   wind_direction_degrees:
     name: "Wind direction"
   wind_gusts_speed:
     name: "Wind gust speed"
   wind_speed:
     name: "Wind speed"
   rain_level:
     name: "Rain level"
   rssi:
     name: "RSSI"

#binary_sensor:
# - platform: bresser5in1_cc1101
#   battery_low:
#     name: "Battery Low"

# sensor:
#   - platform: template
#     name: "Song duration"
#     id: song_duration
# binary_sensor:
#   - platform: template
    
button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: restart
    name: "Restart"
  - platform: template
    name: Reset CC1101
    id: reset_cc1101
    on_press:
      - lambda: |-
          id(weather_station).radioInit();