substitutions:
  # all substitutions for this project
  espidf_version: 5.3.0
  platformio_version: 6.8.1
  friendly_name: Tesla BLE
  device_name: tesla-ble
  device_description: Tesla BLE
  board: esp32dev
  variant: esp32
  flash_size: 4MB
  charging_amps_max: "32"

external_components: !include esphome-tesla-ble/packages/external_components.dashboard.yml

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: yoziru.esphome-tesla-ble
    version: "2024.8.1"
  libraries:
    - https://github.com/yoziru/tesla-ble.git#870b9dd6ae5af57ce2d39ee68dfa997a2f3f1320

logger:
  level: INFO

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_hotspot_password

captive_portal:

packages:
  board: !include esphome-tesla-ble/packages/board.yml
  common: !include esphome-tesla-ble/packages/common.yml
  project: !include esphome-tesla-ble/packages/project.yml
  client: !include esphome-tesla-ble/packages/client.yml
  # for ESPHome Dashboard, use this instead of external_components

# dashboard_import:
#  package_import_url: github://yoziru/esphome-tesla-ble/tesla-ble.example.yml
