substitutions:
  name: "interruttore-saletta-mansarda"
  friendly_name: "Saletta mansarda"

  use_ip_address: 192.168.2.141 # Usato da esphome per monitor e upload

  wifi_ssid: !secret wifi_dmz_ssid
  wifi_password: !secret wifi_dmz_password

#esp32_ble_tracker:
#  scan_parameters:
#    active: True
#    continuous: false

packages:
  # Configurazione di base
  device_base: !include includes/tx_ultimate_base.yaml

  # Connessione MQTT
  mqtt_client: !include includes/mqtt_client.yaml

  # Supporto Voice Assistant
  va: !include
    file: includes/tx_ultimate_voice_assistant.yaml
    vars:
      mic_lrclk_pin: GPIO3
      mic_bclk_pin: GPIO1
      mic_sdata_pin: GPIO0

  # Configurazione leds
  leds: !include includes/tx_ultimate_leds_3_zone.yaml

  # Relè e luci locali
  light_1: !include
    file: includes/tx_ultimate_light.yaml
    vars:
      id: relay_1
      relay_index: 0
      name: "Saletta mansarda"
      pin: ${relay_2_pin}
  light_2: !include
    file: includes/tx_ultimate_light.yaml
    vars:
      id: relay_2
      relay_index: 1
      name: "Sala mansarda"
      pin: ${relay_1_pin}
  light_3: !include
    file: includes/tx_ultimate_mqtt_relay.yaml
    vars:
      id: relay_3
      relay_index: 2
      subscribe_topic: "sonoff_mini_06/stat/POWER"
      value_on: "ON"
      command_topic: "sonoff_mini_06/cmnd/Power1"
      command_toggle: "TOGGLE"


script:
  - id: !extend on_release
    then:
      - if:
          condition:
            lambda: "return index == 0;"
          then:
            - light.toggle: relay_1
          else:
            - if:
                condition:
                  lambda: "return index == 1;"
                then:
                  - light.toggle: relay_2
                else:
                  - script.execute: mqtt_toggle_relay_3

  - id: !extend on_swipe_right
    then:
      - mqtt.publish:
          topic: sonoff_dualr2_03/cmnd/ShutterStopOpen
          payload: ""
  - id: !extend on_swipe_left
    then:
      - mqtt.publish:
          topic: sonoff_dualr2_03/cmnd/ShutterStopClose
          payload: ""
