substitutions:
  name: "interruttore-soggiorno-cucina"
  friendly_name: "Soggiorno Cucina"

  use_ip_address: 192.168.2.146 # Usato da esphome per monitor e upload

  wifi_ssid: !secret wifi_dmz_ssid
  wifi_password: !secret wifi_dmz_password

#esp32_ble_tracker:
#  scan_parameters:
#    active: True
#    continuous: false

packages:
  # Connessione MQTT
  mqtt_client: !include includes/mqtt_client.yaml

  # Configurazione di base
  device_base: !include includes/tx_ultimate_base.yaml

  # Supporto Voice Assistant
  va: !include
    file: includes/tx_ultimate_voice_assistant.yaml
    vars:
      mic_lrclk_pin: GPIO3
      mic_bclk_pin: GPIO1
      mic_sdata_pin: GPIO0

  # Configurazione leds
  leds: !include includes/tx_ultimate_leds_3_zone.yaml

  # Relè e luci locali
  light_1: !include
    file: includes/tx_ultimate_light.yaml
    vars:
      id: relay_1
      relay_index: 0
      name: "Cucina"
      pin: ${relay_1_pin}
  light_2: !include
    file: includes/tx_ultimate_mqtt_relay.yaml
    vars:
      id: relay_3
      relay_index: 1
      subscribe_topic: "interruttore-soggiorno-corr/light/soggiorno_sinistra/state"
      value_on: "ON"
      mqtt_json_key: "state"
      command_topic: "interruttore-soggiorno-corr/light/soggiorno_sinistra/command"
      command_toggle: "{ \"state\": \"TOGGLE\" }"
  light_3: !include
    file: includes/tx_ultimate_mqtt_relay.yaml
    vars:
      id: relay_3
      relay_index: 2
      subscribe_topic: "interruttore-soggiorno-corr/light/soggiorno_destra/state"
      value_on: "ON"
      mqtt_json_key: "state"
      command_topic: "interruttore-soggiorno-corri/light/soggiorno_destra/command"
      command_toggle: "{ \"state\": \"TOGGLE\" }"

# Topic verso altri esphome:      "interruttore-soggiorno-cucina/light/cucina/command"
# Valore:       "{ "state": "TOGGLE" }"

script:
  - id: !extend on_release
    then:
      - if:
          condition:
            lambda: "return index == 0;"
          then:
            - light.toggle: relay_1
          else:
            - if:
                condition:
                  lambda: "return index == 1;"
                then:
                  - light.toggle: relay_2
                else:
                  - script.execute: mqtt_toggle_relay_3
