substitutions:
  name: "interruttore-camera-emanuele"
  friendly_name: "Camera Emanuele"

  use_ip_address: 192.168.2.142 # Usato da esphome per monitor e upload

  wifi_ssid: !secret wifi_dmz_ssid
  wifi_password: !secret wifi_dmz_password

#esp32_ble_tracker:
#  scan_parameters:
#    active: True
#    continuous: false

packages:
  # Connessione MQTT
  mqtt_client: !include includes/mqtt_client.yaml

  # Configurazione di base
  device_base: !include includes/tx_ultimate_base.yaml

  # Supporto Voice Assistant
  va: !include
    file: includes/tx_ultimate_voice_assistant.yaml
    vars:
      mic_lrclk_pin: GPIO1
      mic_bclk_pin: GPIO3
      mic_sdata_pin: GPIO0

  # Configurazione leds
  leds: !include includes/tx_ultimate_leds_1_zone.yaml

  # Relè e luci locali
  light_1: !include
    file: includes/tx_ultimate_light.yaml
    vars:
      id: relay_1
      relay_index: 0
      name: "Camera Emanuele"
      pin: ${relay_1_pin}

script:
  - id: !extend on_release
    then:
      - light.toggle: relay_1
