substitutions:
  device_name: valvola-giardino
  device_comment: "Dispositivo per irrigazione giardino e lettura umidita"
  friendly_name: "Valvola giardino"
#  moltiplicatore_voltaggio: 10.477
#  moltiplicatore_voltaggio: 3 # Lettura voltaggio scala da 0-1 -> 0-3.3V
  moltiplicatore_voltaggio: 7.14
  offset_voltaggio: 0.8

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
  comment: ${device_comment}
  
esp8266:
  board: esp12e
  restore_from_flash: True

factory_reset:
  resets_required: 5
  max_delay: 10s

wifi:
#  ssid: !secret wifi_dmz_ssid
#  password: !secret wifi_dmz_password
  ssid: !secret wifi_garage_ssid
  password: !secret wifi_garage_password
  use_address: 192.168.2.224

  ap:
    ssid: "${friendly_name} AP"
    password: !secret wifi_hotspot_password

captive_portal:

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret api_key

web_server:
  port: 80

logger:
  baud_rate: 0

packages:
  syslog: !include includes/syslog.yaml

switch:
  - platform: gpio
    id: valve_open_gpio
    name: "Valvola"
    pin: GPIO12
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - switch.turn_off: valve_close_gpio
      - output.turn_on: blue_led_output
    on_turn_off:
      - switch.turn_on: valve_close_gpio
      - output.turn_off: blue_led_output

  - platform: gpio
    id: valve_close_gpio
    internal: true
    pin: GPIO13
    restore_mode: ALWAYS_ON



status_led:
  pin: GPIO4

output:
  - platform: gpio
    id: blue_led_output
    pin: GPIO5

  - platform: gpio
    id: moisture_sensor
#    name: "Moisture sensor"
    pin: GPIO3
#    restore_mode: ALWAYS_ON

sensor:
  - platform: adc
    id: adc_moisture
    pin: A0
    name: "Umidita terreno"
    update_interval: never
    samples: 5
    filters:
      - multiply: ${moltiplicatore_voltaggio}
      - lambda: |-
          return 1.0 - x;
      - offset: ${offset_voltaggio}
    on_value: 
      then:
        - output.turn_off: moisture_sensor

binary_sensor:
  - platform: gpio
    id: push_button
    pin: GPIO14
    internal: true
    on_press:
      - switch.toggle: valve_open_gpio

button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: restart
    name: "Restart"

interval:
  - interval: 10s
    then:
      - script.execute: read_moisture

script:
  - id: read_moisture
    then: 
      - output.turn_on: moisture_sensor   # accendi alimentazione
      - delay: 500ms                      # aspetta stabilizzazione
      - component.update: adc_moisture