substitutions:
  audio_lrclk_pin: GPIO4
  audio_bclk_pin: GPIO2
  audio_sdata_pin: GPIO15

  vibra_time_wake_word: 50ms
  vibra_time_ww_off: 200ms

  vibra_time_response: 50ms
  vibra_time_response_off: 100ms

  text_not_understood: "Mi dispiace, non ho capito"

esphome:
  includes:
    - audio/timer_finished.h
    - audio/wake_word_triggered.h

#external_components:
#  - source:
#      type: git
#      url: https://github.com/esphome/home-assistant-voice-pe
#      ref: dev
#    components:
#      - micro_wake_word
#      - microphone
#      - nabu_microphone
#      - voice_assistant
#    refresh: 0s

micro_wake_word:
#  model: okay_nabu
  id: mww
  models:
    - model: https://github.com/kahrendt/microWakeWord/releases/download/okay_nabu_20241205.4/okay_nabu.json
#    - model: https://github.com/kahrendt/microWakeWord/releases/download/stop/stop.json
  microphone: asr_mic
  on_wake_word_detected:
    - lambda: 'ESP_LOGI("custom", "Wake word detected: %s", wake_word.c_str());'
    - if:
        condition:
          switch.is_on: timer_ringing_int
        then:
          - switch.turn_off: timer_ringing_int
        else:
          - if:
              condition:
                lambda: return (wake_word != "Stop");
              then:
                - script.execute: sound_beep
            #    - micro_wake_word.stop
                - voice_assistant.start:
                    wake_word: !lambda return wake_word;
                - light.turn_on:
                    id: leds
                    red: 0
                    green: 0
                    blue: 1
                    brightness: 1
              else:
                - script.execute: restore_wake_word

button:
  - id: vibra_intent
    platform: output
    output: vibra_output
    duration: ${vibra_time_response}
    internal: true
  - id: vibra_ww
    platform: output
    output: vibra_output
    duration: ${vibra_time_wake_word}
    internal: true

  - platform: template
    name: Start/Stop assistant
    id: start_assistant
    entity_category: config
    on_press:
      - if:
          condition:
            voice_assistant.is_running
          then:
            - voice_assistant.stop
            - script.execute: refresh_led_default
            - script.execute: restore_wake_word
          else:
            - if:
                condition:
                  micro_wake_word.is_running
                then:
                  - micro_wake_word.stop
                  - wait_until:
                      not:
                        micro_wake_word.is_running
            - voice_assistant.start
            - light.turn_on:
                id: leds
                red: 0
                green: 0
                blue: 1
                brightness: 1
#          effect: "Scan"
#      - if:
#          condition:
#            - switch.is_on: use_wake_word
#          then:
#            - wait_until:
#                condition:
#                  not:
#                    - voice_assistant.is_running
#                timeout: 30s
#            - lambda: id(va).set_use_wake_word(true);
#            - voice_assistant.start_continuous
  - platform: template
    name: Test speaker
    id: test_speaker
    entity_category: config
    on_press:
      - script.execute: sound_beep

globals:
  - id: !extend ww_switch
    initial_value: use_wake_word
    restore_value: no
  
#  - id: !extend va_glob
#    initial_value: va
#    restore_value: no

  - id: !extend start_assistant_button
    type: template_::TemplateButton*
    initial_value: start_assistant
    restore_value: no

  - id: !extend timer_ringing
    type: template_::TemplateSwitch*
    initial_value: timer_ringing_int
    restore_value: no

    

switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    on_turn_on:
      - globals.set:
          id: wakeword_enabled
          value: 'true'
      - micro_wake_word.start
      - delay: 250ms
      - script.execute: refresh_led_default

    on_turn_off:
      - globals.set:
          id: wakeword_enabled
          value: 'false'
      - micro_wake_word.stop
      - delay: 250ms
      - script.execute: refresh_led_default

  - platform: template
    id: timer_ringing_int
    name: "Ring timer"
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - globals.set:
          id: suspend_refresh
          value: "true"
      - script.execute: timer_start_ringing
    on_turn_off: 
      then:
        - globals.set:
            id: suspend_refresh
            value: "false"
        - script.stop: timer_start_ringing
        - script.execute: restore_wake_word

i2s_audio:
  - id: audio_mic_i2s
    i2s_lrclk_pin: ${mic_lrclk_pin}
    i2s_bclk_pin: ${mic_bclk_pin}
  - id: audio_i2s
    i2s_lrclk_pin: ${audio_lrclk_pin}
    i2s_bclk_pin: ${audio_bclk_pin}

speaker:
  - id: audio_out
    platform: i2s_audio
    dac_type: external
    i2s_dout_pin: ${audio_sdata_pin}
    i2s_audio_id: audio_i2s
    i2s_comm_fmt: stand_msb
    timeout: 100ms
    channel: mono
    bits_per_sample: 16bit
    sample_rate: 16000
    buffer_duration: 1500ms

number:
  - name: Speaker Volume
    id: volume
    platform: template
    entity_category: config
    min_value: 0
    max_value: 1.0
    step: 0.05
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 1
    on_value:
      - lambda: id(audio_out).set_volume(x);

microphone:
  - platform: i2s_audio
    i2s_audio_id: audio_mic_i2s
    i2s_din_pin: ${mic_sdata_pin}
    adc_type: external
    id: asr_mic
    pdm: false


voice_assistant:
  id: va
  microphone: asr_mic
  speaker: audio_out
  use_wake_word: false
  noise_suppression_level: 4
  auto_gain: 31dBFS
  volume_multiplier: 15.0
  on_stt_vad_start:
    - globals.set:
        id: suspend_refresh
        value: "true"
    - light.turn_on:
        id: leds
        red: 0
        green: 0
        blue: 1
        brightness: 1
        effect: "Scan"
  on_stt_vad_end:
    - globals.set:
        id: suspend_refresh
        value: "true"
    - light.turn_on:
        id: leds
        red: 0
        green: 1
        blue: 0
        brightness: 1
        effect: "Scan"
  on_client_connected:
    then:
      - script.execute: restore_wake_word

  on_tts_start:
    - if:
        condition:
          lambda: 'return x == "${text_not_understood}";'
        then:
          - light.turn_on:
              id: leds
              red: 1
              green: 0
              blue: 0
              brightness: 1
              effect: "None"
#              effect: "Scan"
        else:
          - light.turn_on:
              id: leds
              effect: "None"
#              effect: "Rainbow"
              red: 0
              green: 1
              blue: 0
              brightness: 1
  on_tts_stream_end:
    - globals.set:
        id: suspend_refresh
        value: "false"
    - script.execute: restore_wake_word

  on_idle:
    - globals.set:
        id: suspend_refresh
        value: "false"
    - script.execute: restore_wake_word

  on_error:
    - globals.set:
        id: suspend_refresh
        value: "false"
    - script.execute: restore_wake_word
  on_timer_finished:
    - switch.turn_on: timer_ringing_int

script:
  - id: restore_wake_word
    then:
      - if:
          condition:
            switch.is_on: use_wake_word
          then:
            - micro_wake_word.start
          else:
            - micro_wake_word.stop
      - delay: 250ms
      - script.execute: refresh_led_default


  - id: sound_beep
    then:
      - if:
          condition:
            not:
              - speaker.is_playing
          then:
            - lambda: id(audio_out).start();
            - delay: 50ms
            - lambda: id(audio_out).play(wake_word_triggered, wake_word_triggered_len);

  - id: timer_start_ringing
    then:
      - light.turn_on:
          id: leds
          brightness: !lambda "return id(timer_ringing_color)[3]/100.0;"
          red: !lambda "return id(timer_ringing_color)[0]/100.0;"
          green: !lambda "return id(timer_ringing_color)[1]/100.0;"
          blue:  !lambda "return id(timer_ringing_color)[2]/100.0;"
          effect: ${timer_ringing_effect}
      - script.execute: timer_perform_ringing
      - delay: 1min
      - switch.turn_off: timer_ringing_int

  - id: timer_perform_ringing
    then:
      - script.execute: refresh_led_default
      - voice_assistant.stop:
      - delay: 100ms
      - lambda: |- 
          id(audio_out).set_timeout(1200);
          id(audio_out).start();
      - delay: 50ms
      - while:
          condition:
            switch.is_on: timer_ringing_int
          then:
            - lambda: |-
                ESP_LOGI("custom", "Playing timer audio file");
                id(audio_out).play(timer_finished, timer_finished_len);
            - delay: 924ms # 500ms + 424ms audio file duration
      - wait_until:
          not:
            speaker.is_playing:
