substitutions:
  audio_lrclk_pin: GPIO4
  audio_bclk_pin: GPIO2
  audio_sdata_pin: GPIO15

  vibra_time_wake_word: 50ms
  vibra_time_ww_off: 200ms

  vibra_time_response: 50ms
  vibra_time_response_off: 100ms

  text_not_understood: "Mi dispiace, non ho capito"

esphome:
  includes:
    - audio/timer_finished.h
    - audio/wake_word_triggered.h

#external_components:
#  - source:
#      type: git
#      url: https://github.com/esphome/home-assistant-voice-pe
#      ref: dev
#    components:
#      - micro_wake_word
#      - microphone
#      - nabu_microphone
#      - voice_assistant
#    refresh: 0s

micro_wake_word:
#  model: okay_nabu
  id: mww
  models:
    - model: https://github.com/kahrendt/microWakeWord/releases/download/okay_nabu_20241205.4/okay_nabu.json
#      id: okay_nabu
#    - model: https://github.com/kahrendt/microWakeWord/releases/download/stop/stop.json
#      id: stop
#      internal: true
#  vad:
#    model: https://github.com/kahrendt/microWakeWord/releases/download/v2.1_models/vad.json
  microphone: asr_mic
  on_wake_word_detected:
    - script.execute: sound_beep
#    - micro_wake_word.stop
    - voice_assistant.start:
        wake_word: !lambda return wake_word;
    - light.turn_on:
        id: leds
        red: 0
        green: 0
        blue: 1
        brightness: 1
#        effect: "Scan"
#  vad:
#    model: https://github.com/esphome/micro-wake-word-models/raw/main/models/v2/vad.json

button:
  - id: vibra_intent
    platform: output
    output: vibra_output
    duration: ${vibra_time_response}
    internal: true
  - id: vibra_ww
    platform: output
    output: vibra_output
    duration: ${vibra_time_wake_word}
    internal: true

  - platform: template
    name: Start assistant
    id: start_assistant
    entity_category: config
    on_press:
      - if:
          condition:
            micro_wake_word.is_running
          then:
            - micro_wake_word.stop
            - wait_until:
                not:
                  micro_wake_word.is_running
      - globals.set:
          id: va_capturing
          value: "true"
      - voice_assistant.start
      - light.turn_on:
          id: leds
          red: 0
          green: 0
          blue: 1
          brightness: 1
#          effect: "Scan"
#      - if:
#          condition:
#            - switch.is_on: use_wake_word
#          then:
#            - wait_until:
#                condition:
#                  not:
#                    - voice_assistant.is_running
#                timeout: 30s
#            - lambda: id(va).set_use_wake_word(true);
#            - voice_assistant.start_continuous
  - platform: template
    name: Test speaker
    id: test_speaker
    entity_category: config
    on_press:
      - script.execute: sound_beep

globals:
  - id: !extend ww_switch
    initial_value: use_wake_word
    restore_value: no
  - id: !extend start_assistant_button
    type: template_::TemplateButton*
    initial_value: start_assistant
    restore_value: no

  - id: va_capturing
    type: bool
    initial_value: 'false'
    restore_value: no

switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: ALWAYS_OFF
    entity_category: config
    on_turn_on:
      - script.execute: micro_wake_word_start

#      - if:
#          condition:
#            not:
#              - voice_assistant.is_running
#          then:
#            - voice_assistant.start_continuous
##            - light.turn_on:
##                id: leds_wakeword
##                brightness: !lambda "return id(va_color)[3]/100.0;"
##                red: !lambda "return id(va_color)[0]/100.0;"
##                green: !lambda "return id(va_color)[1]/100.0;"
##                blue:  !lambda "return id(va_color)[2]/100.0;"
##     - script.execute: reset_led
    on_turn_off:
      - micro_wake_word.stop
#      - voice_assistant.stop
      # - lambda: id(va).set_use_wake_word(false);
      - globals.set:
          id: va_state
          value: 'false'
      - script.execute: refresh_led_default



#media_player:
#  - platform: i2s_audio
#    id: media_out
#    name: ${friendly_name} Player
#    dac_type: external
#    i2s_dout_pin: ${audio_sdata_pin}
#    i2s_audio_id: audio_i2s
#    i2s_comm_fmt: lsb
#    mode: stereo

i2s_audio:
  - id: audio_mic_i2s
    i2s_lrclk_pin: ${mic_lrclk_pin}
    i2s_bclk_pin: ${mic_bclk_pin}
  - id: audio_i2s
    i2s_lrclk_pin: ${audio_lrclk_pin}
    i2s_bclk_pin: ${audio_bclk_pin}

speaker:
  - id: audio_out
    platform: i2s_audio
    dac_type: external
    i2s_dout_pin: ${audio_sdata_pin}
    i2s_audio_id: audio_i2s
    i2s_comm_fmt: stand_msb
    timeout: 100ms
    channel: mono
    bits_per_sample: 16bit
    sample_rate: 8000
    buffer_duration: 1500ms

number:
  - name: Speaker Volume
    id: volume
    platform: template
    entity_category: config
    min_value: 0
    max_value: 2.0
    step: 0.05
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0.85
    on_value:
      - lambda: id(audio_out).set_volume(x);

microphone:
#  - platform: nabu_microphone
#    i2s_audio_id: audio_mic_i2s
#    i2s_din_pin: ${mic_sdata_pin}
#    adc_type: external
# #   i2s_mode: secondary
#    channel_0:
#      id: asr_mic
#      amplify_shift: 0
##    channel_1:
##      id: comm_mic
##      amplify_shift: 2
#    id: mic_i2s
#    pdm: false
  - platform: i2s_audio
    i2s_audio_id: audio_mic_i2s
    i2s_din_pin: ${mic_sdata_pin}
    adc_type: external
    id: asr_mic
    pdm: false

esp_adf:


voice_assistant:
  id: va
  microphone: asr_mic
  speaker: audio_out
#  media_player: media_out
#  micro_wake_word: mww
  vad_threshold: 5
  use_wake_word: false
  noise_suppression_level: 4
  auto_gain: 31dBFS
  volume_multiplier: 15.0
  on_stt_vad_start:
    - globals.set:
        id: va_capturing
        value: "true"
    - light.turn_on:
        id: leds
        red: 0
        green: 1
        blue: 0
        brightness: 1
#        effect: "Scan"
  on_wake_word_detected:
    - script.execute: sound_beep
    - globals.set:
        id: va_capturing
        value: "true"
    - light.turn_on:
        id: leds
        red: 0
        green: 0
        blue: 1
        brightness: 1
#        effect: "Scan"

#  on_stt_vad_end:
#    - script.execute: sound_beep
#    - delay: 160ms
#    - script.execute: sound_beep
#  on_intent_start:
#    - button.press: vibra_intent
  on_tts_start:
    - globals.set:
        id: va_capturing
        value: "false"
    - if:
        condition:
          lambda: 'return x == "${text_not_understood}";'
        then:
          - light.turn_on:
              id: leds
              red: 1
              green: 0
              blue: 0
              brightness: 1
              effect: "None"
#              effect: "Scan"
        else:
          - light.turn_on:
              id: leds
              effect: "None"
#              effect: "Rainbow"
              red: 0
              green: 1
              blue: 0
              brightness: 1
  on_tts_stream_end:
    - delay: 1s
    - script.execute: refresh_led_full_off_default
#    - repeat:
#        count: 2
#        then:
#          - button.press: vibra_intent
#          - delay: ${vibra_time_response_off}
#    - delay: 2s
#    - light.turn_off:
#        id: leds
#        transition_length: ${transition_length}
#    - delay: ${transition_length}
#    - script.execute: refresh_led_default
#  on_start:
#    - if:
#        condition:
#          - lambda: "return id(va).is_continuous();"
#        then:
#          - globals.set:
#              id: va_state
#              value: 'true'
#          - script.execute: refresh_led_default
  on_end:
    - if:
        condition:
          - lambda: "return id(va_capturing);"
        then:
          - globals.set:
              id: va_capturing
              value: "false"
          - globals.set:
              id: va_state
              value: 'false'
#          - delay: 2s
          - script.execute: refresh_led_full_off_default
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - script.execute: micro_wake_word_start
#          - lambda: id(va).set_use_wake_word(true);
#          - voice_assistant.start_continuous:

  on_error:
    - script.execute: refresh_led_default
#    - light.turn_on:
#        id: leds
#        red: 1
#        green: 0
#        blue: 0
#    - delay: 2s
#    - light.turn_off: leds

#  on_client_connected:
#    - if:
#        condition:
#          switch.is_on: use_wake_word
#        then:
#          - voice_assistant.start_continuous:
#          - script.execute: reset_led
#  on_client_disconnected:
#    - if:
#        condition:
#          switch.is_on: use_wake_word
#        then:
#          - voice_assistant.stop:
##          - light.turn_off: leds

script:
  - id: micro_wake_word_start
    then:
      - micro_wake_word.start
      - globals.set:
          id: va_state
          value: 'true'
      - script.execute: refresh_led_default

  - id: sound_beep
    then:
      - if:
          condition:
            not:
              - speaker.is_playing
#                  id: external_speaker
          then:
            - lambda: id(audio_out).start();
            - delay: 50ms
            - lambda: id(audio_out).play(wake_word_triggered, wake_word_triggered_len);
            - wait_until:
                not:
                  speaker.is_playing

  - id: sound_key_click
    then:
      - if:
          condition:
            not:
              - speaker.is_playing
#                  id: external_speaker
          then:
            - speaker.play:
                id: audio_out
                data: [0x01,0x02,0x04,0x06,0x07,0x08,0x08,0x06,0x01,0xFA,0xF4,0xEF,0xEE,0xF1,0xF7,0xFF,0x07,0x0E,0x11,0x11,0x10,0x0C,0x06,0xFF,0xF8,0xF1,0xEC,0xEA,0xEC,0xF2,0xF9,0xFF,0x05,0x0A,0x10,0x14,0x17,0x17,0x14,0x0B,0xFD,0xED,
                  0xE0,0xD9,0xDB,0xE6,0xF7,0x0A,0x19,0x20,0x1E,0x14,0x05,0xF4,0xE5,0xDF,0xE4,0xF4,0x0C,0x24,0x36,0x3D,0x35,0x20,0xFF,0xDD,0xC0,0xAE,0xA9,0xB0,0xC4,0xE0,0x03,0x26,0x48,0x62,0x70,0x6D,0x59,0x35,0x08,0xD8,0xAC,0x8D,0x80,
                  0x85,0x9C,0xC1,0xF0,0x21,0x4E,0x6F,0x7F,0x7A,0x63,0x3D,0x0F,0xE0,0xB7,0x9B,0x90,0x96,0xAC,0xCE,0xF6,0x1D,0x3C,0x50,0x55,0x4D,0x3A,0x20,0x04,0xEC,0xD8,0xCC,0xC9,0xCD,0xD8,0xE8,0xF9,0x0A,0x17,0x1F,0x20,0x1C,0x12,0x07,
                  0xFC,0xF2,0xEC,0xEB,0xED,0xF3,0xFA,0x02,0x0A,0x10,0x12,0x12,0x0E,0x07,0xFE,0xF5,0xED,0xEA,0xEB,0xEF,0xF7,0x00,0x0A,0x10,0x13,0x12,0x0F,0x09,0x02,0xFB,0xF5,0xF3,0xF2,0xF3,0xF6,0xFB,0xFF,0x03,0x05,0x07,0x08,0x07,0x05,
                  0x03,0x01,0xFF,0xFE,0xFC,0xFB,0xFB,0xFC,0xFC,0xFD,0xFE,0xFF,0x00,0x01,0x02,0x02,0x01]
            - wait_until:
                not:
                  - speaker.is_playing
#                      id: external_speaker

