substitutions:

  vibra_time_wake_word: 50ms
  vibra_time_ww_off: 200ms

  vibra_time_response: 50ms
  vibra_time_response_off: 100ms

  text_not_understood: "Mi dispiace, non ho capito"

esp32:
  cpu_frequency: 240MHz
#esphome:
#  includes:
#    - audio/wake_word_triggered.h

#external_components:
#  - source:
#      type: git
#      url: https://github.com/esphome/home-assistant-voice-pe
#      ref: dev
#    components:
#      - micro_wake_word
#      - microphone
#      - nabu_microphone
#      - voice_assistant
#    refresh: 0s

micro_wake_word:
#  model: okay_nabu
  id: mww
  models:
    - model: https://github.com/kahrendt/microWakeWord/releases/download/okay_nabu_20241205.4/okay_nabu.json
#    - model: https://github.com/kahrendt/microWakeWord/releases/download/stop/stop.json
  microphone: asr_mic
  on_wake_word_detected:
    - lambda: 'ESP_LOGI("custom", "Wake word detected: %s", wake_word.c_str());'
    - if:
        condition:
          switch.is_on: timer_ringing_int
        then:
          - switch.turn_off: timer_ringing_int
        else:
          - if:
              condition:
                lambda: return (wake_word != "Stop");
              then:
                - script.execute: sound_beep
            #    - micro_wake_word.stop
                - voice_assistant.start:
                    wake_word: !lambda return wake_word;
                - light.turn_on:
                    id: leds
                    red: 0
                    green: 0
                    blue: 1
                    brightness: 1
              else:
                - script.execute: restore_wake_word

button:
  - id: vibra_intent
    platform: output
    output: vibra_output
    duration: ${vibra_time_response}
    internal: true
  - id: vibra_ww
    platform: output
    output: vibra_output
    duration: ${vibra_time_wake_word}
    internal: true

  - platform: template
    name: Start/Stop assistant
    id: start_assistant
    entity_category: config
    on_press:
      - if:
          condition:
            voice_assistant.is_running
          then:
            - voice_assistant.stop
            - script.execute: refresh_led_default
            - script.execute: restore_wake_word
          else:
            - if:
                condition:
                  micro_wake_word.is_running
                then:
                  - micro_wake_word.stop
                  - wait_until:
                      not:
                        micro_wake_word.is_running
            - voice_assistant.start
            - light.turn_on:
                id: leds
                red: 0
                green: 0
                blue: 1
                brightness: 1
#          effect: "Scan"
#      - if:
#          condition:
#            - switch.is_on: use_wake_word
#          then:
#            - wait_until:
#                condition:
#                  not:
#                    - voice_assistant.is_running
#                timeout: 30s
#            - lambda: id(va).set_use_wake_word(true);
#            - voice_assistant.start_continuous
  - platform: template
    name: Test speaker
    id: test_speaker
    entity_category: config
    on_press:
      - script.execute: sound_beep

globals:
  - id: !extend ww_switch
    initial_value: use_wake_word
    restore_value: no
  
#  - id: !extend va_glob
#    initial_value: va
#    restore_value: no

  - id: !extend start_assistant_button
    type: template_::TemplateButton*
    initial_value: start_assistant
    restore_value: no

  - id: !extend timer_ringing
    type: template_::TemplateSwitch*
    initial_value: timer_ringing_int
    restore_value: no

    

switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    on_turn_on:
      - globals.set:
          id: wakeword_enabled
          value: 'true'
      - micro_wake_word.start
      - delay: 250ms
      - script.execute: refresh_led_default

    on_turn_off:
      - globals.set:
          id: wakeword_enabled
          value: 'false'
      - micro_wake_word.stop
      - delay: 250ms
      - script.execute: refresh_led_default

  - platform: template
    id: timer_ringing_int
    name: "Ring timer"
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - globals.set:
          id: suspend_refresh
          value: "true"
      - mixer_speaker.apply_ducking:
            id: media_mixing_input
            decibel_reduction: 20
            duration: 0.0s
      - script.execute: timer_start_ringing
    on_turn_off: 
      then:
        - globals.set:
            id: suspend_refresh
            value: "false"
        - script.stop: timer_start_ringing
        - if:
            condition:
              media_player.is_announcing:
            then:
              media_player.stop:
                announcement: true
        # Set back ducking ratio to zero
        - mixer_speaker.apply_ducking:
            id: media_mixing_input
            decibel_reduction: 0
            duration: 1.0s
        - script.execute: restore_wake_word

i2s_audio:
  - id: audio_mic_i2s
    i2s_lrclk_pin: ${mic_lrclk_pin}
    i2s_bclk_pin: ${mic_bclk_pin}



microphone:
  - platform: i2s_audio
    i2s_audio_id: audio_mic_i2s
    i2s_din_pin: ${mic_sdata_pin}
    adc_type: external
    id: asr_mic
    pdm: false
    channel: left
    sample_rate: 16000


voice_assistant:
  id: va
  microphone: asr_mic
#  speaker: audio_out
  media_player: va_media_player
  use_wake_word: false
  noise_suppression_level: 4
  auto_gain: 31dBFS
  volume_multiplier: 15.0
  on_stt_vad_start:
    - globals.set:
        id: suspend_refresh
        value: "true"
    - light.turn_on:
        id: leds
        red: 0
        green: 0
        blue: 1
        brightness: 1
        effect: "Scan"
  on_stt_vad_end:
    - globals.set:
        id: suspend_refresh
        value: "true"
    - light.turn_on:
        id: leds
        red: 0
        green: 1
        blue: 0
        brightness: 1
        effect: "Scan"
  on_client_connected:
    then:
      - script.execute: restore_wake_word

  on_tts_start:
    - micro_wake_word.stop:
    - if:
        condition:
          lambda: 'return x == "${text_not_understood}";'
        then:
          - light.turn_on:
              id: leds
              red: 1
              green: 0
              blue: 0
              brightness: 1
              effect: "None"
#              effect: "Scan"
        else:
          - light.turn_on:
              id: leds
              effect: "None"
#              effect: "Rainbow"
              red: 0
              green: 1
              blue: 0
              brightness: 1
  on_start:
    - mixer_speaker.apply_ducking:
        id: media_mixing_input
        decibel_reduction: 50  # Number of dB quieter; higher implies more quiet, 0 implies full volume
        duration: 0.0s         # The duration of the transition (default is no transition)
  on_end:
    - wait_until:
        not:
          voice_assistant.is_running:
    # Stop ducking audio.
    - mixer_speaker.apply_ducking:
        id: media_mixing_input
        decibel_reduction: 0
        duration: 1.0s
    - globals.set:
        id: suspend_refresh
        value: "false"
    - script.execute: restore_wake_word

  on_idle:
    - mixer_speaker.apply_ducking:
        id: media_mixing_input
        decibel_reduction: 0
        duration: 1.0s
    - globals.set:
        id: suspend_refresh
        value: "false"
    - script.execute: restore_wake_word

  on_error:
    - globals.set:
        id: suspend_refresh
        value: "false"
    - script.execute: restore_wake_word
  on_timer_finished:
    - switch.turn_on: timer_ringing_int

media_player:
  - platform: speaker
    id: va_media_player
    name: Media Player
    codec_support_enabled: true
    buffer_size: 250000
    task_stack_in_psram: false
    volume_initial: 100%
    announcement_pipeline:
      format: WAV
      speaker: announcement_mixing_input
      num_channels: 1
      sample_rate: ${play_sample_rate}000
    media_pipeline:
      format: FLAC
      speaker: media_mixing_input
      num_channels: 1
      sample_rate: ${play_sample_rate}000
    on_announcement:
      - mixer_speaker.apply_ducking:
          id: media_mixing_input
          decibel_reduction: 20
          duration: 0.0s
    on_state:
      if:
        condition:
          and:
            - switch.is_off: timer_ringing_int
            - not:
                voice_assistant.is_running:
            - not:
                media_player.is_announcing:
        then:
          - mixer_speaker.apply_ducking:
              id: media_mixing_input
              decibel_reduction: 0
              duration: 1.0s
    files:
      - id: wake_word_wav
        file: audio/wake_word_triggered_${play_sample_rate}.wav # Placed in the yaml directory. Should be encoded with a 48000 Hz sample rate, mono or stereo audio, and 16 bits per sample.
      - id: timer_finished_wav
        file: audio/timer_finished_${play_sample_rate}.wav # Placed in the yaml directory. Should be encoded with a 48000 Hz sample rate, mono or stereo audio, and 16 bits per sample.


script:
  - id: restore_wake_word
    then:
      - if:
          condition:
            switch.is_on: use_wake_word
          then:
            - delay: 1000ms
            - micro_wake_word.start
          else:
            - micro_wake_word.stop
      - delay: 250ms
      - script.execute: refresh_led_default


  - id: sound_beep
    then:
      - media_player.speaker.play_on_device_media_file:
          media_file: wake_word_wav
          announcement: true

  - id: timer_start_ringing
    then:
      - light.turn_on:
          id: leds
          brightness: !lambda "return id(timer_ringing_color)[3]/100.0;"
          red: !lambda "return id(timer_ringing_color)[0]/100.0;"
          green: !lambda "return id(timer_ringing_color)[1]/100.0;"
          blue:  !lambda "return id(timer_ringing_color)[2]/100.0;"
          effect: ${timer_ringing_effect}
      - script.execute: timer_perform_ringing
      - delay: 1min
      - switch.turn_off: timer_ringing_int

  - id: timer_perform_ringing
    then:
      - script.execute: refresh_led_default
      - voice_assistant.stop:
      - delay: 100ms
      - while:
          condition:
            switch.is_on: timer_ringing_int
          then:
            - media_player.speaker.play_on_device_media_file:
                media_file: timer_finished_wav
                announcement: true
            # Wait until the alarm sound starts playing
            - wait_until:
                media_player.is_announcing:
            # Wait until the alarm sound stops playing
            - wait_until:
                not:
                  media_player.is_announcing:
            - delay: 500ms
      - wait_until:
          not:
            media_player.is_announcing:
